FORMAT: 1A
HOST: http://padex.com/api/v1

# PADAPI

PADAPI is a simple API allowing for the retrieval of all information related to the game Puzzle and Dragons.

## Leader Skill [/leader_skill/thin/{leader_skill_id}]

### View a Thin Leader Skill [GET]

+ Parameters
    + leader_skill_id (integer) - ID of an Leader Skill

+ Response 200 (application/json)

        {
            "id": 2169,
            "name": "Eternal Dragon Pact - Fragrem",
            "effect": "Light attribute cards HP x2, ATK x2.5. Light attribute cards ATK x1.3 on the turn a skill is used. ( Multiple skills will not stack )",
            "original_effect": "2x HP & 2.5x ATK for Light Att.; ATK increases slightly for Light Att. when skills used"
        }

### View all Thin Leader Skill [GET /leader_skill/thin/{?offset,limit}]
    
+ Parameters
    + offset (integer, optional) - ID of the first Leader Skill to be returned
        + Default: 0
    + limit (integer, optional) - Number of Leader Skill to return
        + Default: 10 
    
+ Response 200 (application/json)

        {
            "leader_skills": [
                {
                    "id": 2169,
                    "name": "Eternal Dragon Pact - Fragrem",
                    "effect": "Light attribute cards HP x2, ATK x2.5. Light attribute cards ATK x1.3 on the turn a skill is used. ( Multiple skills will not stack )",
                    "original_effect": "2x HP & 2.5x ATK for Light Att.; ATK increases slightly for Light Att. when skills used"
                }, 
                {
                    "id": 2206,
                    "name": "Mechanical Light Star of Gemini",
                    "effect": " Matched attribute ATK x4 when matching exactly 5 connected orbs with at least 1 enhanced orb. 30% Fire, Water, Wood & Dark damage reduction.",
                    "original_effect": "4x ATK for Att. erasing 5 Orbs with 1+ enhanced; reduces damage from non-Light Att. enemies"
                },
                {
                    "id": 1829,
                    "name": "Scarlet Talisman",
                    "effect": "ATK x2.5 when attacking with Fire & Light orb types at the same time. Matched attribute ATK x2.5 when matching exactly 5 connected orbs with at least 1 enhanced orb.",
                    "original_effect": "2.5x ATK when Fire & Light attack at once; 2.5x ATK for Att. erasing 5 Orbs including enhanced"
                }
            ],
            "total_leader_skills": 10
        }

### View a Leader Skill [GET /leader_skill/{leader_skill_id}]

+ Parameters
    + leader_skill_id (integer) - ID of an Leader Skill

+ Response 200 (application/json)

        {
            "id": 2169,
            "name": "Eternal Dragon Pact - Fragrem",
            "effect": "Light attribute cards HP x2, ATK x2.5. Light attribute cards ATK x1.3 on the turn a skill is used. ( Multiple skills will not stack )",
            "original_effect": "2x HP & 2.5x ATK for Light Att.; ATK increases slightly for Light Att. when skills used",
            "owned_by_monsters": [
                2440,
                2441
            ]
        }

### View all Leader Skill [GET /leader_skill/{?offset,limit}]
    
+ Parameters
    + offset (integer, optional) - ID of the first Leader Skill to be returned
        + Default: 0
    + limit (integer, optional) - Number of Leader Skill to return
        + Default: 10 
    
+ Response 200 (application/json)

        {
            "leader_skills": [
                {
                    "id": 2169,
                    "name": "Eternal Dragon Pact - Fragrem",
                    "effect": "Light attribute cards HP x2, ATK x2.5. Light attribute cards ATK x1.3 on the turn a skill is used. ( Multiple skills will not stack )",
                    "original_effect": "2x HP & 2.5x ATK for Light Att.; ATK increases slightly for Light Att. when skills used",
                    "owned_by_monsters": [
                        2440,
                        2441
                    ]
                }, 
                {
                    "id": 2206,
                    "name": "Mechanical Light Star of Gemini",
                    "effect": " Matched attribute ATK x4 when matching exactly 5 connected orbs with at least 1 enhanced orb. 30% Fire, Water, Wood & Dark damage reduction.",
                    "original_effect": "4x ATK for Att. erasing 5 Orbs with 1+ enhanced; reduces damage from non-Light Att. enemies",
                    "owned_by_monsters": [
                        2421,
                        2422
                    ]
                },
                {
                    "id": 1829,
                    "name": "Scarlet Talisman",
                    "effect": "ATK x2.5 when attacking with Fire & Light orb types at the same time. Matched attribute ATK x2.5 when matching exactly 5 connected orbs with at least 1 enhanced orb.",
                    "original_effect": "2.5x ATK when Fire & Light attack at once; 2.5x ATK for Att. erasing 5 Orbs including enhanced",
                    "owned_by_monsters": [
                        2141,
                        2142
                    ]
                }
            ],
            "total_leader_skills": 10
        }

## Active Skill [/active_skill/thin/{active_skill_id}]

+ Parameters
    + active_skill_id (integer) - ID of an Active Skill

### View a Thin Active Skill [GET]

+ Response 200 (application/json)

        {
            "id": 1567,
            "name": "Shine Flare Ring",
            "effect": "Change all orbs to Fire, Light & Heart orbs. Reduces cooldown of other skills by 1 turn.",
            "original_effect": "Changes Orbs to Fire, Light & Heal Orbs; other allies' skills charged by 1 turn",
            "max_cd": 15,
            "min_cd": 10,
            "max_lvl": 6
        }

### View all Thin Active Skill [GET /active_skill/thin/{?offset,limit}]
    
+ Parameters
    + offset (integer, optional) - ID of the first Active Skill to be returned
        + Default: 0
    + limit (integer, optional) - Number of Active Skill to return
        + Default: 10 
    
+ Response 200 (application/json)

        {
            "active_skills": [
                {
                    "id": 1320,
                    "name": "Dimension Formation - Scarlet Sun",
                    "effect": "Randomly spawn 3 Fire & Light orbs from non Fire & Light orbs. Reduces cooldown of other skills by 1 turn.",
                    "original_effect": "Creates 3 Fire and Light Orbs each at random; other allies' skills charged by 1 turn",
                    "max_cd": 12,
                    "min_cd": 7,
                    "max_lvl": 6
                }, 
                {
                    "id": 1567,
                    "name": "Shine Flare Ring",
                    "effect": "Change all orbs to Fire, Light & Heart orbs. Reduces cooldown of other skills by 1 turn.",
                    "original_effect": "Changes Orbs to Fire, Light & Heal Orbs; other allies' skills charged by 1 turn",
                    "max_cd": 15,
                    "min_cd": 10,
                    "max_lvl": 6
                },
                {
                    "id": 1583,
                    "name": "Astrocharge - Light",
                    "effect": "Change Heart, Jammer, Poison & Mortal Poison orbs to Light orbs. Reduces cooldown of other skills by 1 turn.",
                    "original_effect": "Changes Jammers, Poison & Heal Orbs to Light Orbs; other allies' skills charged by 1 turn",
                    "max_cd": 12,
                    "min_cd": 7,
                    "max_lvl": 6
                }
            ],
            "total_active_skills": 10
        }

### View an Active Skill [GET /active_skill/{active_skill_id}]

+ Parameters
    + active_skill_id (integer) - ID of an Active Skill

+ Response 200 (application/json)

        {
            "id": 1567,
            "name": "Shine Flare Ring",
            "effect": "Change all orbs to Fire, Light & Heart orbs. Reduces cooldown of other skills by 1 turn.",
            "original_effect": "Changes Orbs to Fire, Light & Heal Orbs; other allies' skills charged by 1 turn",
            "max_cd": 15,
            "min_cd": 10,
            "max_lvl": 6,
            "owned_by_monsters": [
                430,
                2440,
                2441
            ]
        }

### View all Active Skill [GET /active_skill/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Active Skill to be returned
        + Default: 0
    + limit (integer, optional) - Number of Active Skill to return
        + Default: 10
        
+ Response 200 (application/json)

        {
            "active_skills": [
                {
                    "id": 1320,
                    "name": "Dimension Formation - Scarlet Sun",
                    "effect": "Randomly spawn 3 Fire & Light orbs from non Fire & Light orbs. Reduces cooldown of other skills by 1 turn.",
                    "original_effect": "Creates 3 Fire and Light Orbs each at random; other allies' skills charged by 1 turn",
                    "max_cd": 12,
                    "min_cd": 7,
                    "max_lvl": 6,
                    "owned_by_monsters": [
                        1176,
                        2141,
                        2142
                    ]
                }, 
                {
                    "id": 1567,
                    "name": "Shine Flare Ring",
                    "effect": "Change all orbs to Fire, Light & Heart orbs. Reduces cooldown of other skills by 1 turn.",
                    "original_effect": "Changes Orbs to Fire, Light & Heal Orbs; other allies' skills charged by 1 turn",
                    "max_cd": 15,
                    "min_cd": 10,
                    "max_lvl": 6,
                    "owned_by_monsters": [
                        430,
                        2440,
                        2441
                    ]
                },
                {
                    "id": 1583,
                    "name": "Astrocharge - Light",
                    "effect": "Change Heart, Jammer, Poison & Mortal Poison orbs to Light orbs. Reduces cooldown of other skills by 1 turn.",
                    "original_effect": "Changes Jammers, Poison & Heal Orbs to Light Orbs; other allies' skills charged by 1 turn",
                    "max_cd": 12,
                    "min_cd": 7,
                    "max_lvl": 6,
                    "owned_by_monsters": [
                        2421,
                        2422,
                        2645
                    ]
                }
            ],
            "total_active_skills": 10
        }

## Awoken Skill [/awoken_skill/thin/{awoken_skill_id}]

### View a Thin Awoken Skill [GET]

+ Parameters
    + awoken_skill_id (integer) - ID of an Awoken Skill

+ Response 200 (application/json)

        {
            "id": 29,
            "name": "Two-Pronged Attack",
            "effect": "Eliminating exactly 4 connected orbs of the same color for 1.5x ATK on 2 enemies",
            "img": "/img/29.png"
        }

### View all Thin Awoken Skill [GET /awoken_skill/thin/{?offset,limit}]
    
+ Parameters
    + offset (integer, optional) - ID of the first Awoken Skill to be returned
        + Default: 0
    + limit (integer, optional) - Number of Awoken Skill to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "awoken_skills": [
                {
                    "id": 23,
                    "name": "Skill Boost",
                    "effect": "The entire team starts with 1 turn worth of skills charged",
                    "img": "/img/23.png"
                },
                {
                    "id": 24,
                    "name": "Enhanced Fire Attribute",
                    "effect": "Eliminating 1 row of fire orbs will increase your fire damage by 10%",
                    "img": "/img/24.png"
                },
                {
                    "id": 29,
                    "name": "Two-Pronged Attack",
                    "effect": "Eliminating exactly 4 connected orbs of the same color for 1.5x ATK on 2 enemies",
                    "img": "/img/29.png"
                }
            ],
            "total_awoken_skills": 10
        }

### View an Awoken Skill [GET /awoken_skill/{awoken_skill_id}]

+ Parameters
    + awoken_skill_id (integer) - ID of an Awoken Skill

+ Response 200 (application/json)

        {
            "id": 29,
            "name": "Two-Pronged Attack",
            "effect": "Eliminating exactly 4 connected orbs of the same color for 1.5x ATK on 2 enemies",
            "img": "/img/29.png",
            "owned_by_monsters": [
                1727,
                1728,
                1729,
                1730
            ]
        }

### View all Awoken Skill [GET /awoken_skill/{?offset,limit}]
    
+ Parameters
    + offset (integer, optional) - ID of the first Awoken Skill to be returned
        + Default: 0
    + limit (integer, optional) - Number of Awoken Skill to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "awoken_skills": [
                {
                    "id": 23,
                    "name": "Skill Boost",
                    "effect": "The entire team starts with 1 turn worth of skills charged",
                    "img": "/img/23.png",
                    "owned_by_monsters": [
                        394,
                        395,
                        1928
                    ]
                },
                {
                    "id": 24,
                    "name": "Enhanced Fire Attribute",
                    "effect": "Eliminating 1 row of fire orbs will increase your fire damage by 10%",
                    "img": "/img/24.png",
                    "owned_by_monsters": [
                        652,
                        1344,
                        2392
                    ]
                },
                {
                    "id": 29,
                    "name": "Two-Pronged Attack",
                    "effect": "Eliminating exactly 4 connected orbs of the same color for 1.5x ATK on 2 enemies",
                    "img": "/img/29.png",
                    "owned_by_monsters": [
                        1727,
                        1728,
                        1729,
                        1730
                    ]
                }
            ],
            "total_awoken_skills": 10
        }

## Monster Series [/monster_series/thin/{monster_series_id}]

### View a Thin Monster Series [GET]

+ Parameters
    + monster_series_id (integer) - ID of an Monster Series

+ Response 200 (application/json)

        {
            "id": 54,
            "name": "God Fest. Exclusive"
        }

### View all Thin Monster Series [GET /monster_series/thin/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Monster Series to be returned
        + Default: 0
    + limit (integer, optional) - Number of Monster Series to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "monster_series": [
                {
                    "id": 54,
                    "name": "God Fest. Exclusive"
                },
                {
                    "id": 55,
                    "name": "Japanese Mythology"
                },
                {
                    "id": 56,
                    "name": "Stone Dragon"
                }
            ],
            "total_monster_series": 10
        }

### View a Monster Series [GET /monster_series/{monster_series_id}]

+ Parameters
    + monster_series_id (integer) - ID of an Monster Series

+ Response 200 (application/json)

        {
            "id": 54,
            "name": "God Fest. Exclusive",
            "monsters_in_series": [
                2714,
                2744,
                2745
            ]
        }

### View all Monster Series [GET /monster_series/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Monster Series to be returned
        + Default: 0
    + limit (integer, optional) - Number of Monster Series to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "monster_series": [
                {
                    "id": 54,
                    "name": "God Fest. Exclusive",
                    "monsters_in_series": [
                        2714,
                        2744,
                        2745
                    ]
                },
                {
                    "id": 55,
                    "name": "Japanese Mythology",
                    "monsters_in_series": [
                        717,
                        718,
                        777
                    ]
                },
                {
                    "id": 56,
                    "name": "Stone Dragon",
                    "monster_series": [
                        737,
                        738,
                        739
                    ]
                }
            ],
            "total_monster_series": 10
        }

## Type [/type/thin/{type_id}]

### View a Thin Type [GET]

+ Parameters
    + type_id (integer) - ID of a Type

+ Response 200 (application/json)

        {
            "id": 5,
            "name": "Attacker"
        }

### View all Thin Type [GET /type/thin/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Type to be returned
        + Default: 0
    + limit (integer, optional) - Number of Type to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "types": [
                {
                    "id": 5,
                    "name": "Attacker"
                },
                {
                    "id": 6,
                    "name": "God"
                },
                {
                    "id": 7,
                    "name": "Evo Material"
                }
            ],
            "total_types": 10
        }

### View a Type [GET /type/{type_id}]

+ Parameters
    + type_id (integer) - ID of a Type

+ Response 200 (application/json)

        {
            "id": 5,
            "name": "Attacker",
            "primary_type_owned_by": [
                2812,
                2815,
                2818
            ],
            "secondary_type_owned_by": [
                2747,
                2748,
                2750
            ],
            "ternary_type_owned_by": [
                1473,
                1727,
                1728
            ]
        }

### View all Type [GET /type/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Type to be returned
        + Default: 0
    + limit (integer, optional) - Number of Type to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "types": [
                {
                    "id": 5,
                    "name": "Attacker",
                    "primary_type_owned_by": [
                        2812,
                        2815,
                        2818
    
                    ],
                    "secondary_type_owned_by": [
                        2747,
                        2748,
                        2750
    
                    ],
                    "ternary_type_owned_by": [
                        1473,
                        1727,
                        1728
    
                    ]
                },
                {
                    "id": 6,
                    "name": "God",
                    "primary_type_owned_by": [
                        2742,
                        2752,
                        2790
    
                    ],
                    "secondary_type_owned_by": [
                        2700,
                        2701,
                        2702
    
                    ],
                    "ternary_type_owned_by": [
                        535,
                        1206,
                        2127
    
                    ]
                },
                {
                    "id": 7,
                    "name": "Evo Material",
                    "primary_type_owned_by": [
                        1085,
                        1086,
                        1087
    
                    ],
                    "secondary_type_owned_by": [],
                    "ternary_type_owned_by": []
                }
            ],
            "total_types": 10
        }





## Element [/element/thin/{element_id}]

### View a Thin Element [GET]

+ Parameters
    + element_id (integer) - ID of a Element

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Fire"
        }

### View all Thin Element [GET /element/thin/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Element to be returned
        + Default: 0
    + limit (integer, optional) - Number of Element to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "element": [
                {
                    "id": 1,
                    "name": "Fire"
                },
                {
                    "id": 2,
                    "name": "Water"
                },
                {
                    "id": 3,
                    "name": "Wood"
                }
            ],
            "total_element": 5
        }

### View a Element [GET /type/{element_id}]

+ Parameters
    + element_id (integer) - ID of a Element

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Fire",
            "primary_element_owned_by": [
                2800,
                2804,
                2805
            ],
            "secondary_type_owned_by": [
                2800,
                2803,
                2806
            ]
        }

### View all Element [GET /type/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Element to be returned
        + Default: 0
    + limit (integer, optional) - Number of Element to return
        + Default: 10 

+ Response 200 (application/json)

        {
            "element": [
                {
                    "id": 1,
                    "name": "Fire",
                    "primary_element_owned_by": [
                        2800,
                        2804,
                        2805
                    ],
                    "secondary_element_owned_by": [
                        2800,
                        2803,
                        2806
                    ]
                },
                {
                    "id": 2,
                    "name": "Water",
                    "primary_element_owned_by": [
                        2730,
                        2731,
                        2748
                    ],
                    "secondary_element_owned_by": [
                        2745,
                        2749,
                        2751
                    ]
                },
                {
                    "id": 3,
                    "name": "Wood",
                    "primary_element_owned_by": [
                        2810,
                        2811,
                        2814
                    ],
                    "secondary_element_owned_by": [
                        2750,
                        2775,
                        2782
                    ]
                }
            ],
            "total_element": 5
        }

## Monster [/monster/{monster_id}]

### View a Monster [GET]

+ Parameters
    + monster_id (integer) - ID of a Monster

+ Response 200 (application/json)

        {
            "id": 2441,
            "name": "Judging-Claw Orange Dragonbound, Saria",
            "rarity": 6,
            "primary_type": 1,
            "secondary_type": 3,
            "ternary_type": null,
            "primary_element": 4,
            "secondary_element": 1,
            "team_cost": 50,
            "sells_for_monster_points": 15000,
            "min_lvl": 1,
            "max_lvl": 99,
            "min_hp": 1647,
            "max_hp": 4118,
            "min_atk": 607,
            "max_atk": 1518,
            "min_rcv": 48,
            "max_rcv": 120,
            "min_sell_value": 870,
            "max_sell_value": 86130,
            "min_exp_feed": 2100,
            "max_exp_feed": 207900,
            "exp_needed": 5000000,
            "evolves_to": [],
            "evolves_from": 131,
            "monster_series": 54,
            "active_skill": 1567,
            "leader_skill": 2169,
            "awoken_skills": [
                27,
                27,
                29,
                23,
                21
            ],
            "dropped_in_dungeons": [],
            "img": "/img/2441.png",
            "thmb": "/thmb/2441.png"
        }

### View all Monster [GET /monster/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Monster to be returned
        + Default: 0
    + limit (integer, optional) - Number of Monster to return
        + Default: 10 
        
+ Response 200 (application/json)

        {
            "monsters": [
                {
                    "id": 2441,
                    "name": "Judging-Claw Orange Dragonbound, Saria",
                    "rarity": 6,
                    "primary_type": 1,
                    "secondary_type": 3,
                    "ternary_type": null,
                    "primary_element": 4,
                    "secondary_element": 1,
                    "team_cost": 50,
                    "sells_for_monster_points": 15000,
                    "min_lvl": 1,
                    "max_lvl": 99,
                    "min_hp": 1647,
                    "max_hp": 4118,
                    "min_atk": 607,
                    "max_atk": 1518,
                    "min_rcv": 48,
                    "max_rcv": 120,
                    "min_sell_value": 870,
                    "max_sell_value": 86130,
                    "min_exp_feed": 2100,
                    "max_exp_feed": 207900,
                    "exp_needed": 5000000,
                    "evolves_to": [],
                    "evolves_from": 2440,
                    "evolution_chain": 301,
                    "monster_series": 54,
                    "active_skill": 1567,
                    "leader_skill": 2169,
                    "awoken_skills": [
                        27,
                        27,
                        29,
                        23,
                        21
                    ],
                    "dropped_in_dungeons": [],
                    "img": "/img/2441.png",
                    "thmb": "/thmb/2441.png"
                },
                {
                    "id": 2442,
                    "name": "Blue Dragonbound, Ryune",
                    "rarity": 6,
                    "primary_type": 1,
                    "secondary_type": null,
                    "ternary_type": null,
                    "primary_element": 2,
                    "secondary_element": null,
                    "team_cost": 40,
                    "sells_for_monster_points": 50000,
                    "min_lvl": 1,
                    "max_lvl": 50,
                    "min_hp": 712,
                    "max_hp": 1709,
                    "min_atk": 352,
                    "max_atk": 845,
                    "min_rcv": 38,
                    "max_rcv": 91,
                    "min_sell_value": 720,
                    "max_sell_value": 36000,
                    "min_exp_feed": 1725,
                    "max_exp_feed": 86250,
                    "exp_needed": 5000000,
                    "evolves_to": [
                        2443
                    ],
                    "evolves_from": null,
                    "evolution_chain": 300,
                    "monster_series": 54,
                    "active_skill": 1568,
                    "leader_skill": 2170,
                    "awoken_skills": [],
                    "dropped_in_dungeons": [],
                    "img": "/img/2441.png",
                    "thmb": "/thmb/2441.png"
                }
            ],
            "total_monsters": 2
        }

## Dungeon [/dungeon/{dungeon_id}]

### View a Dungeon [GET]

+ Parameters
    + dungeon_id (integer) - ID of a Dungeon

+ Response 200 (application/json)

        {
            "id": 680,
            "name": "Sky Prison - Mythical",
            "random_encounters": [],
            "major_encounters": [
                {
                    "common_id": 160,
                    "hit_points": 75900,
                    "attack": 4770,
                    "defense": 60,
                    "turn": 1,
                    "floor": 1,
                    "quantity": 3,
                    "drops": [
                        160
                    ],
                    "moves": []
                },
                {
                    "common_id": 916,
                    "hit_points": 3056111,
                    "attack": null,
                    "defense": 200,
                    "turn": 1,
                    "floor": 4,
                    "quantity": 1,
                    "drops": [
                        916
                    ],
                    "moves": [
                        {
                            "name": "Angrilit",
                            "attack": 56751,
                            "attack_condition": "100% Chance. Will use when alone",
                            "effect": "Increases damage to 300% for the next 999 turns"
                        },
                        {
                            "name": "Devilit Poison",
                            "attack": null,
                            "attack_condition": "100% Chance. Will use every other turn",
                            "effect": "Converts 6 Random orbs into Poison orbs"
                        }
                    ]
                }
            ]
        }

### View all Dungeon [GET /dungeon/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Dungeon to be returned
        + Default: 0
    + limit (integer, optional) - Number of Dungeon to return
        + Default: 5 
        
+ Response 200 (application/json)

        {
            "dungeons": [
                {
                    "id": 680,
                    "name": "Sky Prison - Mythical",
                    "random_encounters": [],
                    "major_encounters": [
                        {
                            "common_id": 160,
                            "hit_points": 75900,
                            "attack": 4770,
                            "defense": 60,
                            "turn": 1,
                            "floor": 1,
                            "quantity": 3,
                            "drops": [
                                160
                            ],
                            "moves": []
                        },
                        {
                            "common_id": 916,
                            "hit_points": 3056111,
                            "attack": null,
                            "defense": 200,
                            "turn": 1,
                            "floor": 4,
                            "quantity": 1,
                            "drops": [
                                916
                            ],
                            "moves": [
                                {
                                    "name": "Angrilit",
                                    "attack": 56751,
                                    "attack_condition": "100% Chance. Will use when alone",
                                    "effect": "Increases damage to 300% for the next 999 turns"
                                },
                                {
                                    "name": "Devilit Poison",
                                    "attack": null,
                                    "attack_condition": "100% Chance. Will use every other turn",
                                    "effect": "Converts 6 Random orbs into Poison orbs"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": 810,
                    "name": "Divine Queen of Darkness",
                    "random_encounters": [
                        {
                            "common_id": 192,
                            "hit_points": 46650,
                            "attack": 5460,
                            "defnse": 2200,
                            "turn": 2,
                            "drops": [
                                192
                            ],
                            "moves": []
                        },
                        {
                            "common_id": 198,
                            "hit_points": 51150,
                            "attack": 5550,
                            "defnse": 2200,
                            "turn": 2,
                            "drops": [
                                198
                            ],
                            "moves": []
                        }
                    ],
                    "major_encounters": [
                        {
                            "common_id": 189,
                            "hit_points": 2569319,
                            "attack": 12354,
                            "defense": 372,
                            "turn": 1,
                            "floor": 10,
                            "quantity": 1,
                            "drops": [
                                189
                            ],
                            "moves": []
                        }
                    ]
                }
            ],
            "total_dungeons": 2
        }

## Evolution [/evolution/{evolution_id}]

### View a Evolution [GET]

+ Parameters
    + evolution_id (integer) - ID of a Evolution

+ Response 200 (application/json)

        {
            "id": 301,
            "from_monster": 2440,
            "current_monster": 2441,
            "to_monster": null
        }

### View all Evolution [GET /evolution/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Evolution to be returned
        + Default: 0
    + limit (integer, optional) - Number of Evolution to return
        + Default: 10

+ Response 200 (application/json)

        {
            "evolutions": [
                {
                    "id": 301,
                    "from_monster": 2440,
                    "current_monster": 2441,
                    "to_monster": null
                },  
                {
                    "id": 302,
                    "from_monster": null,
                    "current_monster": 2440,
                    "to_monster": 2441
                }
            ],
            "total_evolutions": 10
        }